called all functions from suggested packages via foo::bar() now, i.e., these don't rely on any functionality being put on the search path
hence all require("foo") have been omitted from the code with only one
exception: read.shapefile() actually wants package:shapefiles on the search
path...

-> checks ok with current R-devel



git-svn-id: svn://svn.r-forge.r-project.org/svnroot/bayesr@1076 edb9625f-4e0d-4859-8d74-9fd3b1da38cb